- action:
  - data:
      entity_id: scene.daylights
    service: scene.turn_on
  - data:
      entity_id: switch.synology_home_mode
    service: switch.turn_on
  alias: Alarm off 09:00-19:00
  condition:
  - after: 09:00
    before: '19:00'
    condition: time
  id: '1506347308883'
  trigger:
  - entity_id: alarm_control_panel.sabbatsvagen_alarm
    from: armed_away
    platform: state
    to: disarmed
- action:
  - data:
      entity_id: scene.eveninglights
    service: scene.turn_on
  - data:
      entity_id: switch.synology_home_mode
    service: switch.turn_on
  alias: Alarm off 19:00-22:30
  condition:
  - after: '19:00'
    before: '22:30'
    condition: time
  id: '1506347621179'
  trigger:
  - entity_id: alarm_control_panel.sabbatsvagen_alarm
    from: armed_away
    platform: state
    to: disarmed
- action:
  - data:
      entity_id: scene.nightlights
    service: scene.turn_on
  - data:
      entity_id: switch.synology_home_mode
    service: switch.turn_on
  alias: Alarm off 22:30-05:00
  condition:
  - after: '22:30'
    before: 05:00
    condition: time
  trigger:
  id: 005857b82b7c40359a54cfe34bfa0751
- id: turn_off_wallplug3
  alias: Stäng av motorvärmaren 1½ timme
  trigger:
  - entity_id: switch.wallplug3_switch
    platform: state
    to: 'on'
  action:
  - delay: 01:30:00
  - data:
      entity_id: switch.wallplug3_switch
    entity_id: switch.wallplug3_switch
    service: switch.turn_off
- id: '1569275044308'
  alias: Kupevärmare På
  trigger:
  - below: '5'
    entity_id: sensor.yr_temperature
    platform: numeric_state
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - after: 06:15
    before: 07:00
    condition: time
  action:
  - data:
      entity_id: switch.wallplug3_switch
    service: switch.turn_on
