homeassistant:
  name: Home
  latitude: 59.427489
  longitude: 17.809095
  elevation: 26
  unit_system: metric
  time_zone: Europe/Stockholm

   ## CUSTOMIZE### Enables configuration UI
#  customize: !include_dir_merge_named customize/
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.51
        - 192.168.1.64
        - 192.168.1.239
        - 192.168.1.172
        - 192.168.1.2
system_health:

config:

# Enables the frontend 
frontend:

mobile_app:

recorder:
  db_url: !secret db_url
  
panel_iframe: !include panel_iframe.yaml

http:
#  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 3
  #ssl_certificate: !secret ssl_cert
  #ssl_key: !secret ssl_key
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.122
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

#tellstick:
  #host: "192.168.1.87"
 # port: [50800, 50801]

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automations/
script old: !include scripts/scripts.yaml
script: !include scripts.yaml
scene: !include_dir_list scenes
#ios: !include ios.yaml



# Devices #
apple_tv: !include devices/apple_tv.yaml
camera: !include devices/cameras.yaml
#device_tracker: !include devices/device_tracker.yaml 
zwave: !include devices/zwave.yaml 
sensor: !include devices/sensors.yaml 
verisure: !include devices/verisure.yaml 
switch: !include devices/switches.yaml 
media_player: !include devices/media_players.yaml 
input_boolean: !include devices/input_booleans.yaml 
input_number: !include devices/input_number.yaml
input_select: !include devices/input_selects.yaml
binary_sensor: !include devices/binary_sensors.yaml
calendar: !include devices/calendars.yaml
shell_command: !include devices/shell_commands.yaml
stream:

## SmartIR
smartir:

climate:
  - platform: smartir
    name: Luftvärmepump
    unique_id: varmepump
    device_code: 9999
    controller_data: 192.168.1.163
    temperature_sensor: sensor.brandvarnare_matsal_temperature

#  - platform: zwave

##

python_script:

asuswrt:
  host: 192.168.1.1
  username: !secret router_user
  password: !secret router_password

alexa:
  smart_home: !include alexa.yaml

#google_assistant: !include google_assistant.yaml 

#homekit: !include siri.yaml  

#### ZONES ####
zone:
  name: Home
  latitude: !secret lati
  longitude: !secret long
  radius: 50
  icon: mdi:home
  #friendly_name: Hemma

zone 2:
  name: Johans arbete
  latitude: 59.331700
  longitude: 18.06883
  radius: 100
  icon: mdi:worker 

zone 3:
  name: Jakobsbergs Station
  latitude: 59.423696
  longitude: 17.833053
  radius: 100
  icon: mdi:train 

zone 4:
  name: Centralen
  latitude: 59.330450
  longitude: 18.057650
  radius: 100
  icon: mdi:train
  
zone 5:
  name: Danderyds sjukhus
  latitude: 59.3922251
  longitude: 18.0383817
  radius: 100
  icon: mdi:hospital 

ifttt:
  key: !secret iftt_key

#################################

