- platform: template
  sensors:
    frontdoor_unlocked:
      friendly_name: "Ytterdörr"
      value_template: "{{ is_state('lock.entredorr','unlocked')}}"

- platform: flic
  host: 192.168.1.122

- platform: workday
  country: SE

- platform: tod
  name: SL Tid
  after: '06:00'
  before: '23:30'
