- platform: synology
  url: https://192.168.1.51:5001
  username: !secret syno_user
  password: !secret syno_pass
  timeout: 15
  verify_ssl: False
  
- platform: mjpeg
  name: iPhone5
  mjpeg_url: http://192.168.1.174/live
  username: !secret cam_user
  password: !secret cam_pass