################# Alarm Automationer #####################
- alias: 'NightTime'
  trigger:
    platform: state
    entity_id: input_boolean.nighttime
    to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.inomhuslampor
    - service: lock.lock
      data:
        code: !secret mobil
    - service: alarm_control_panel.alarm_arm_home
      data:
        code: !secret mobil
    - service: homeassistant.turn_off
      entity_id: input_boolean.nighttime
        
- alias: 'Skal larm off 06:00-10:00'
  trigger:
    platform: state
    entity_id: alarm_control_panel.sabbatsvagen_alarm
    from: 'armed_home'
    to: 'disarmed'
  condition:
    condition: time
    after: '06:00'
    before: '10:00'
  action:
    - service: scene.turn_on
      entity_id: scene.morninglights
    - service: switch.turn_on
      entity_id: switch.synology_home_mode
        
- alias: Happens when alarmed away
  trigger:
    platform: state
    entity_id: alarm_control_panel.sabbatsvagen_alarm
    to: armed_away
  action:
    - service: homeassistant.turn_off
      entity_id: group.inomhuslampor_larm
    - service: homeassistant.turn_on
      entity_id: switch.wallplug5
    - service: switch.turn_off
      entity_id: switch.synology_home_mode
