################# Ringklocka Automationer #####################
- alias: 'Play doorbell on audio alert daytime'
  trigger:
    platform: state
    entity_id: switch.ringklocka
    to: 'on'
  condition:
    condition: time
    after: 08:00
    before: '19:15'
  action:
    service: homeassistant.turn_on
    entity_id: script.play_doorbell_on_alert_in_kitchen_daytime

- alias: 'Play doorbell on audio alert evening'
  trigger:
    platform: state
    entity_id: switch.ringklocka
    to: 'on'
  condition:
    condition: time
    after: '19:15'
    before: '23:00'
  action:
    service: homeassistant.turn_on
    entity_id: script.play_doorbell_on_alert_in_kitchen_evening
    
- alias: 'Sätt Ringklocka till off'
  trigger:
    platform: state
    entity_id: switch.ringklocka
    to: 'on'
  action:
    - delay: '5'
    - service: homeassistant.turn_off
      entity_id: switch.ringklocka
    