################# Flic Automationer #####################
- alias: 'Toggle masterbedroom bedlights one click'
  trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da7255e2
      click_type: single
  action:
    service: light.toggle
    entity_id: light.masterbedroomsanglampor_level
    
- alias: 'Toggle masterbedroom spots double-click'
  trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da7255e2
      click_type: double
  action:
    service: light.toggle
    entity_id: light.masterbedroomspottar_level

- alias: 'Toggle masterbedroom evening lights hold'
  trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da7255e2
      click_type: hold
  action:
    - service: light.turn_on
      data:
        brightness: 46
        entity_id:
          - light.masterbedroomsanglampor_level
    - service: light.turn_off
      entity_id: light.masterbedroomspottar_level

