################# Flic Automationer #####################
- alias: 'Toggle masterbedroom bedlights one click'
  trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da7255e2
      click_type: single
  action:
    service: light.toggle
    entity_id: light.masterbedroomsanglampor_level
    
- alias: 'Toggle masterbedroom spots double-click'
  trigger:
    platform: event
    event_type: flic_click
    event_data:
      button_name: flic_80e4da7255e2
      click_type: double
  action:
    service: light.toggle
    entity_id: light.masterbedroomspottar_level