###################### VÄRME Automationer ####################
- alias: Sänk hallgolvets värme
  trigger:
    platform: time
    at: '23:30:00'
  action:
    service: climate.set_temperature
    entity_id: climate.varmegolv_heating
    data:
      temperature: 18

- alias: Höj hallgolvets värme
  trigger:
  - at: 05:45:00
    platform: time
  action:
  - data:
      temperature: 26
    entity_id: climate.varmegolv_heating
    service: climate.set_temperature
    
- alias: Stäng av motorvärmaren 1½ timme
  trigger:
    platform: numeric_state
    entity_id: sensor.wallplug1_power
    above: 100
    for:
      hours: 1
      minutes: 30
      seconds: 0
  action:
    service: switch.turn_off
    entity_id: switch.wallplug1_switch
    
- alias: Stäng av wallplug 1 om uterummet över 19C
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_zw100_multisensor_6_temperature
    above: 19
  action:
    service: switch.turn_off
    entity_id: switch.wallplug1_switch
    
- alias: Sätt på wallplug 1 om uterummet under 17C
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_zw100_multisensor_6_temperature
    below: 17
  action:
    service: switch.turn_on
    entity_id: switch.wallplug1_switch