#################### IOS Automationer ##########################

- alias: 'Startup Notification'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.ios_johan
    data:
      message: Vad skönt, Home Assistant är uppe igen!

- alias: 'Notify iOS app Johan Ringer på dörren'
  trigger:
  - entity_id: switch.ringklocka
    from: 'off'
    platform: state
    to: 'on'
  action:
  - alias: IOS - ringer på dörren
    data:
      data:
        action_data:
        entity_id: camera.entre
        push:
          badge: 1
          category: camera
      message: Någon ringer på dörren!
    service: notify.ios_johan
    
- alias: 'Notify iOS app Johan rörelse baksidan'
  trigger:
    platform: state
    entity_id: binary_sensor.camera_baksidan
    from: 'off'   
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.johan
    state: 'not_home'
  action:
  - alias: IOS - rörelse på baksidan
    data:
      data:
        action_data:
        entity_id: camera.baksidan
        push:
          badge: 5
          category: camera
      message: Rörelse på baksidan!
    service: notify.ios_johan
    
- alias: 'Notify iOS app Johan rörelse framsidan'
  trigger:
    platform: state
    entity_id: binary_sensor.camera_entre
    from: 'off'   
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.johan
    state: 'not_home'
  action:
  - alias: IOS - rörelse på framsidan
    data:
      data:
        action_data:
        entity_id: camera.entre
        push:
          badge: 5
          category: camera
      message: Rörelse på framsidan!
    service: notify.ios_johan

- alias: 'Öppna ytterdörren'
  trigger:
  - event_data:
      actionName: ALLINONE_TRUE
    event_type: ios.notification_action_fired
    platform: event
  - entity_id: input_boolean.unlockdoor
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      code: !secret mobil
    entity_id: lock.entredorr
    service: lock.unlock
  - entity_id: input_boolean.unlockdoor
    service: input_boolean.turn_off

- alias: 'Lås ytterdörren'
  trigger:
  - event_data:
      actionName: ALLINONE_FALSE
    event_type: ios.notification_action_fired
    platform: event
  - entity_id: input_boolean.lockdoor
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      code: !secret mobil
    entity_id: lock.entredorr
    service: lock.lock
  - entity_id: input_boolean.lockdoor
    service: input_boolean.turn_off

- alias: 'Notify iOS app Johan soptunnan'
  trigger:
  - minutes: '/30'
    platform: time
    seconds: 0
  condition:
  - condition: and
    conditions:
    - after: '17:15:00'
      condition: time
      weekday:
      - wed
    - condition: state
      entity_id: input_boolean.soptunna
      state: 'off'
  action:
  - data:
      data:
        action_data:
        push:
          badge: 2
          category: soptunna
      message: Är soptunnan fixad?
    service: notify.ios_johan

- alias: 'Notify iOS app Sanna soptunnan'
  trigger:
  - minutes: '/30'
    platform: time
    seconds: 0
  condition:
  - condition: and
    conditions:
    - after: '17:00:00'
      condition: time
      weekday:
      - wed
    - condition: state
      entity_id: input_boolean.soptunna
      state: 'off'
  action:
  - data:
      data:
        action_data:
        push:
          badge: 2
          category: soptunna
      message: Är soptunnan fixad?
    service: notify.ios_sanna
    
- alias: 'Soptunnan uppe'
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SOPTUNNA_UPPE
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.soptunna

- alias: 'Soptunnan nere'
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SOPTUNNA_NERE
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.soptunna