#################### IOS Automationer ##########################
  
- alias: 'Startup Notification'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.mobile_app_johan
    data:
      message: Vad skönt, Home Assistant är uppe igen!

- alias: 'Notify iOS app Johan Ringer på dörren'
  trigger:
  - platform: state
    entity_id: sensor.popp_access_control_7
    to: '22'
#  condition:
#    condition: template
#    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.sensor.popp_access_control_7.last_changed)) > 120 }}'
  action:
  - alias: IOS - ringer på dörren
    service: notify.mobile_app_johan
    data:
      message: Någon ringer på dörren!
      data:
        push:
          badge: 1
          category: camera
        entity_id: camera.entre
   
- alias: 'Notify iOS app Johan rörelse baksidan'
  trigger:
    platform: state
    entity_id: binary_sensor.camera_baksidan
    from: 'off'   
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.johan_8
    state: 'not_home'
  action:
  - alias: IOS - rörelse på baksidan
    data:
      data:
        action_data:
        entity_id: camera.baksidan
        push:
          badge: 5
          category: camera
      message: Rörelse på baksidan!
    service: notify.mobile_app_johan
    
- alias: 'Notify iOS app Johan rörelse framsidan'
  trigger:
    platform: state
    entity_id: binary_sensor.camera_entre
    from: 'off'   
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.johan_8
    state: 'not_home'
  action:
  - alias: IOS - rörelse på framsidan
    data:
      data:
        action_data:
        entity_id: camera.entre
        push:
          badge: 5
          category: camera
      message: Rörelse på framsidan!
    service: notify.mobile_app_johan

- alias: 'Notify iOS app Johan rörelse baksidan skallarm'
  trigger:
    platform: state
    entity_id: binary_sensor.camera_baksidan
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sabbatsvagen_alarm
    state: 'armed_home'
  action:
  - alias: IOS - rörelse på baksidan
    data:
      data:
        action_data:
        entity_id: camera.baksidan
        push:
          badge: 5
          category: camera
      message: Rörelse på baksidan!
    service: notify.mobile_app_johan

- alias: 'Notify iOS app Johan rörelse framsidan skallarm'
  trigger:
    platform: state
    entity_id: binary_sensor.camera_entre
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sabbatsvagen_alarm
    state: 'armed_home'
  action:
  - alias: IOS - rörelse på framsidan
    data:
      data:
        action_data:
        entity_id: camera.entre
        push:
          badge: 5
          category: camera
      message: Rörelse på framsidan!
    service: notify.mobile_app_johan

- alias: 'Öppna ytterdörren'
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: ALLINONE_TRUE
    - platform: state 
      entity_id: input_boolean.unlockdoor
      to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sabbatsvagen_alarm
    state: 'disarmed'
  action:
    - service: lock.unlock
      entity_id: lock.entredorr
      data:
        code: !secret mobil
    - service: homeassistant.turn_off 
      entity_id: input_boolean.lockdoor 

- alias: 'Lås ytterdörren'
  trigger:
  - event_data:
      actionName: ALLINONE_FALSE
    event_type: ios.notification_action_fired
    platform: event
  - entity_id: input_boolean.lockdoor
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      code: !secret mobil
    entity_id: lock.entredorr
    service: lock.lock
  - service: homeassistant.turn_off
    entity_id: input_boolean.lockdoor

- alias: 'Notify iOS app Johan soptunnan'
  trigger:
    platform: time_pattern
    minutes: '/30'
    seconds: 0
  condition:
  - condition: and
    conditions:
    - after: '17:15:00'
      condition: time
      weekday:
      - wed
    - condition: state
      entity_id: input_boolean.soptunna
      state: 'off'
  action:
  - data:
      data:
        action_data:
        push:
          badge: 2
          category: soptunna
      message: Är soptunnan fixad?
    service: notify.mobile_app_johan

- alias: 'Notify iOS app Sanna soptunnan'
  trigger:
    platform: time_pattern
    minutes: '/30'
    seconds: 0
  condition:
  - condition: and
    conditions:
    - after: '17:00:00'
      condition: time
      weekday:
      - wed
    - condition: state
      entity_id: input_boolean.soptunna
      state: 'off'
  action:
  - data:
      data:
        action_data:
        push:
          badge: 2
          category: soptunna
      message: Är soptunnan fixad?
    service: notify.mobile_app_sanna
    
- alias: 'Soptunnan uppe'
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SOPTUNNA_UPPE
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.soptunna

- alias: 'Soptunnan nere'
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SOPTUNNA_NERE
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.soptunna

